
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: contact_development

  
test:
  <<: *default
  database: contact_test


production:
  <<: *default
  database: contact_production
  username: contact
  password: <%= ENV['CONTACT_DATABASE_PASSWORD'] %>
